# Generated by Django 4.0.3 on 2022-04-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=200)),
                ('parent1', models.CharField(max_length=200)),
                ('parent2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.family')),
            ],
        ),
    ]
