# Generated by Django 4.0.3 on 2022-04-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_child_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.family'),
        ),
    ]
